// ================================================
//  드라마 DRAMA.KR  —  data.js
//  K-Drama Database with Real Poster Images
// ================================================

const GENRES = [
  { id:"all",        label:"All Dramas",  emoji:"🎬", color:"var(--text)",   grad:"linear-gradient(135deg,#1a1a3a,#3a1a5a)" },
  { id:"romance",    label:"Rom-Com",      emoji:"💗", color:"var(--c-romance)",  grad:"linear-gradient(135deg,#3a0020,#7a004a,#ff2d7833)" },
  { id:"comedy",     label:"Comedy",       emoji:"😂", color:"var(--c-comedy)",   grad:"linear-gradient(135deg,#3a2a00,#7a5a00,#fbbf2433)" },
  { id:"thriller",   label:"Thriller",     emoji:"😰", color:"var(--c-thriller)", grad:"linear-gradient(135deg,#3a0000,#7a1010,#ef444433)" },
  { id:"fantasy",    label:"Fantasy",      emoji:"✨", color:"var(--c-fantasy)",  grad:"linear-gradient(135deg,#1a003a,#40007a,#a855f733)" },
  { id:"mystery",    label:"Mystery",      emoji:"🕵️", color:"var(--c-mystery)",  grad:"linear-gradient(135deg,#001a3a,#003a7a,#3b82f633)" },
  { id:"horror",     label:"Horror",       emoji:"👻", color:"var(--c-horror)",   grad:"linear-gradient(135deg,#1a0000,#3a0808,#99000033)" },
  { id:"action",     label:"Action",       emoji:"⚔️", color:"var(--c-action)",   grad:"linear-gradient(135deg,#3a1000,#7a2a00,#f9731633)" },
  { id:"melodrama",  label:"Melodrama",    emoji:"💔", color:"var(--c-melodrama)",grad:"linear-gradient(135deg,#001a15,#003a30,#06d6a033)" },
  { id:"historical", label:"Historical",   emoji:"👑", color:"var(--c-historical)",grad:"linear-gradient(135deg,#2a1800,#4a2a00,#d9770633)" },
];

const DRAMAS = [
  // ──── ROM-COM ──────────────────────────────────────────────────
  {
    id:1,
    title:"Crash Landing on You",
    krTitle:"사랑의 불시착",
    genre:"romance",
    year:2019, episodes:16, rating:9.2,
    network:"tvN",
    // Real TMDB poster
    poster:"https://image.tmdb.org/t/p/w500/mVQQW5EblWL43UrxijFuDhp5BFy.jpg",
    fallback:"🪂",
    cast:["Hyun Bin","Son Ye-jin"],
    tags:["Cross-border love","Military","North Korea","Sweeping"],
    synopsis:"A South Korean heiress accidentally paraglides into North Korea and falls deeply in love with an elite military officer who must hide and protect her at all costs.",
    isNew:false, isTrending:true,
  },
  {
    id:2,
    title:"Business Proposal",
    krTitle:"사내맞선",
    genre:"romance",
    year:2022, episodes:12, rating:8.7,
    network:"SBS",
    poster:"https://image.tmdb.org/t/p/w500/bAhScKFJqNYuVCFaGiUYeaYJdD1.jpg",
    fallback:"💼",
    cast:["Ahn Hyo-seop","Kim Se-jeong"],
    tags:["Office romance","CEO","Disguise","Hilarious"],
    synopsis:"A woman goes on a blind date to scare off her friend's suitor — only to find out he's her company's cold-hearted CEO. Mistaken identities and butterflies ensue.",
    isNew:false, isTrending:true,
  },
  {
    id:3,
    title:"My Love from the Star",
    krTitle:"별에서 온 그대",
    genre:"romance",
    year:2013, episodes:21, rating:9.0,
    network:"SBS",
    poster:"https://image.tmdb.org/t/p/w500/jzdEEA89sKD1qbHUbFWzO0QZRVQ.jpg",
    fallback:"⭐",
    cast:["Kim Soo-hyun","Jun Ji-hyun"],
    tags:["Alien","400 years","Hallyu star","Classic"],
    synopsis:"An alien stranded on Earth for 400 years falls in love with a top Korean celebrity just three months before his scheduled departure. A modern Hallyu classic.",
    isNew:false, isTrending:false,
  },
  {
    id:4,
    title:"Queen In-hyun's Man",
    krTitle:"인현왕후의 남자",
    genre:"romance",
    year:2012, episodes:16, rating:9.1,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/hGJAErzCcMIy2KJywsLPHD3BSNl.jpg",
    fallback:"⏳",
    cast:["Ji Hyun-woo","Yoo In-na"],
    tags:["Time travel","Joseon era","Fate","Hidden gem"],
    synopsis:"A Joseon-era scholar travels through time to the present day and falls for a struggling actress. A beautifully crafted time-travel romance that left fans devastated.",
    isNew:false, isTrending:false,
  },

  // ──── COMEDY ───────────────────────────────────────────────────
  {
    id:5,
    title:"Reply 1988",
    krTitle:"응답하라 1988",
    genre:"comedy",
    year:2015, episodes:20, rating:9.7,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/zZC0KVDOfH38d5m6R6rfCKTkKHH.jpg",
    fallback:"📺",
    cast:["Hyeri","Ryu Jun-yeol","Park Bo-gum"],
    tags:["Nostalgia","1988","Neighborhood","All-time greatest"],
    synopsis:"Life in a Seoul alleyway in 1988 — five friends and their families navigate growing up, first loves, and the passage of time. Universally beloved.",
    isNew:false, isTrending:true,
  },
  {
    id:6,
    title:"Oh My Ghost",
    krTitle:"오 나의 귀신님",
    genre:"comedy",
    year:2015, episodes:16, rating:8.6,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/bQXBO89MHBCLGDV2nrA9QfZMKP7.jpg",
    fallback:"👻",
    cast:["Park Bo-young","Jo Jung-suk"],
    tags:["Body possession","Chef","Supernatural","Charming"],
    synopsis:"A shy kitchen assistant is possessed by a lusty ghost who takes over her body to seduce the celebrity chef she is obsessed with. Hilarious and surprisingly touching.",
    isNew:false, isTrending:false,
  },
  {
    id:7,
    title:"Welcome to Waikiki",
    krTitle:"으라차차 와이키키",
    genre:"comedy",
    year:2018, episodes:16, rating:8.5,
    network:"JTBC",
    poster:"https://image.tmdb.org/t/p/w500/vemcPbSo3LG2L6eZ0BepD5tKPWv.jpg",
    fallback:"🏨",
    cast:["Lee Yi-kyung","Son Seung-won"],
    tags:["Guesthouse","Friends","Slapstick","Ensemble"],
    synopsis:"Three friends running a failing guesthouse have their chaotic lives turned completely upside down when a baby and her young mother suddenly appear on their doorstep.",
    isNew:false, isTrending:false,
  },

  // ──── THRILLER ─────────────────────────────────────────────────
  {
    id:8,
    title:"Stranger",
    krTitle:"비밀의 숲",
    genre:"thriller",
    year:2017, episodes:16, rating:9.4,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/6eaqBg5SG9TrHAcIHaBc0rOFI9s.jpg",
    fallback:"🌲",
    cast:["Cho Seung-woo","Bae Doona"],
    tags:["Corruption","Prosecutor","Police","Masterpiece"],
    synopsis:"A prosecutor with no emotions teams up with a sharp detective to expose corruption reaching the highest levels of government. Widely considered the best Korean thriller.",
    isNew:false, isTrending:true,
  },
  {
    id:9,
    title:"Signal",
    krTitle:"시그널",
    genre:"thriller",
    year:2016, episodes:16, rating:9.3,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/9YkG5XoVJHxhYxMbRfbXtP4INCD.jpg",
    fallback:"📻",
    cast:["Lee Je-hoon","Kim Hye-soo"],
    tags:["Time travel","Cold cases","Walkie-talkie","Mind-blowing"],
    synopsis:"A detective in the present communicates via a mysterious walkie-talkie with a detective from the past to solve cold cases — but changing the past has real consequences.",
    isNew:false, isTrending:false,
  },
  {
    id:10,
    title:"Juvenile Justice",
    krTitle:"소년심판",
    genre:"thriller",
    year:2022, episodes:10, rating:8.9,
    network:"Netflix",
    poster:"https://image.tmdb.org/t/p/w500/8bXOVyMSvVp6REfMPqIBbBIb8RA.jpg",
    fallback:"⚖️",
    cast:["Kim Hye-soo","Kim Mu-yeol"],
    tags:["Legal","Juvenile crime","Dark","Thought-provoking"],
    synopsis:"A judge who despises juvenile offenders is assigned to a juvenile court. A morally complex and gut-wrenching look at broken childhoods and the limits of justice.",
    isNew:false, isTrending:false,
  },

  // ──── FANTASY ──────────────────────────────────────────────────
  {
    id:11,
    title:"Goblin",
    krTitle:"도깨비",
    genre:"fantasy",
    year:2016, episodes:16, rating:9.6,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/n7EnOYFcDKMKaHmZ5OHFVP3MSOC.jpg",
    fallback:"🗡️",
    cast:["Gong Yoo","Kim Go-eun","Lee Dong-wook"],
    tags:["Grim reaper","Immortal","Epic love","Legend"],
    synopsis:"An immortal goblin seeks his human bride who alone can end his eternal suffering, while the Grim Reaper becomes his unlikely roommate. A breathtaking fantasy epic.",
    isNew:false, isTrending:true,
  },
  {
    id:12,
    title:"Alchemy of Souls",
    krTitle:"환혼",
    genre:"fantasy",
    year:2022, episodes:30, rating:9.1,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/gxayOf4EtHEw2NZHE3OUEzFU8Cd.jpg",
    fallback:"🔮",
    cast:["Lee Jae-wook","Jung So-min","Go Youn-jung"],
    tags:["Soul swapping","Mages","Martial arts","Rich world"],
    synopsis:"In a world where mages perform forbidden soul-swapping magic, a powerful assassin trapped in a weak body becomes the bodyguard of a powerful young noble heir.",
    isNew:false, isTrending:false,
  },
  {
    id:13,
    title:"My Demon",
    krTitle:"마이 데몬",
    genre:"fantasy",
    year:2023, episodes:16, rating:8.3,
    network:"SBS",
    poster:"https://image.tmdb.org/t/p/w500/q2pHqQKT8nFrMBXXnm9LxAMEiDc.jpg",
    fallback:"😈",
    cast:["Song Kang","Kim Yoo-jung"],
    tags:["Demon","Contract marriage","Powers","Stylish"],
    synopsis:"A demon who collects souls loses his powers after touching a wealthy heiress and enters a forced contract marriage with her. Irresistible chemistry in a stylized supernatural romance.",
    isNew:true, isTrending:false,
  },

  // ──── MYSTERY ──────────────────────────────────────────────────
  {
    id:14,
    title:"Flower of Evil",
    krTitle:"악의 꽃",
    genre:"mystery",
    year:2020, episodes:16, rating:9.2,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/vFlpHlP0MaWBLwnMWwZ8vCX2dJP.jpg",
    fallback:"🌸",
    cast:["Lee Jun-ki","Moon Chae-won"],
    tags:["Identity","Marriage mystery","Edge-of-seat","Devastating"],
    synopsis:"A detective investigates a serial murder case while slowly suspecting her own husband — a man concealing a dark hidden identity. Brutally tense and unforgettably romantic.",
    isNew:false, isTrending:true,
  },
  {
    id:15,
    title:"Through the Darkness",
    krTitle:"악의 마음을 읽는 자들",
    genre:"mystery",
    year:2022, episodes:12, rating:9.0,
    network:"SBS",
    poster:"https://image.tmdb.org/t/p/w500/gNwNMiL4KI1ndRe9GAvHKTD5Dcr.jpg",
    fallback:"🔍",
    cast:["Kim Nam-gil","Jin Sun-kyu"],
    tags:["Criminal profiling","True crime","80s","Gripping"],
    synopsis:"Based on a true story — Korea's first criminal profiler interviews serial killers to build psychological profiles that can stop future murders. Slow-burn, deeply human.",
    isNew:false, isTrending:false,
  },
  {
    id:16,
    title:"Mouse",
    krTitle:"마우스",
    genre:"mystery",
    year:2021, episodes:20, rating:8.8,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/pabOagVNLlUPrYlxwp36eK9d0aD.jpg",
    fallback:"🐭",
    cast:["Lee Seung-gi","Park Ju-hyun"],
    tags:["Serial killer","Nature vs nurture","Shocking twists","Dark"],
    synopsis:"What if we could detect psychopathy before birth? A police officer relentlessly pursues a serial killer while questioning everything he knows about good, evil, and human nature.",
    isNew:false, isTrending:false,
  },

  // ──── HORROR ───────────────────────────────────────────────────
  {
    id:17,
    title:"Kingdom",
    krTitle:"킹덤",
    genre:"horror",
    year:2019, episodes:12, rating:9.0,
    network:"Netflix",
    poster:"https://image.tmdb.org/t/p/w500/gKMIzT8KT2mMgFCbL2VUZhwxBLs.jpg",
    fallback:"👑",
    cast:["Ju Ji-hoon","Bae Doona"],
    tags:["Zombie","Joseon era","Political intrigue","Cinematic"],
    synopsis:"A Joseon-era crown prince investigates a mysterious plague reanimating the dead while battling a deadly political conspiracy that threatens his throne. Utterly stunning.",
    isNew:false, isTrending:true,
  },
  {
    id:18,
    title:"All of Us Are Dead",
    krTitle:"지금 우리 학교는",
    genre:"horror",
    year:2022, episodes:12, rating:8.4,
    network:"Netflix",
    poster:"https://image.tmdb.org/t/p/w500/6mFkhAO6bFSRJJbCrjzp6bBvWqH.jpg",
    fallback:"🧟",
    cast:["Park Ji-hoo","Yoon Chan-young"],
    tags:["Zombie","High school","Survival","Heartbreaking"],
    synopsis:"A zombie virus outbreak traps students inside their high school. Visceral, terrifying, and surprisingly emotional — a love story set inside the apocalypse.",
    isNew:false, isTrending:false,
  },
  {
    id:19,
    title:"Strangers from Hell",
    krTitle:"타인은 지옥이다",
    genre:"horror",
    year:2019, episodes:10, rating:8.7,
    network:"OCN",
    poster:"https://image.tmdb.org/t/p/w500/cL7VKrRhYYVf7SnEyJKB7oJGOQf.jpg",
    fallback:"🏚️",
    cast:["Im Si-wan","Lee Dong-wook"],
    tags:["Psychological horror","Neighbors","Claustrophobic","Disturbing"],
    synopsis:"A young man moves into a cheap Seoul rooftop apartment and begins to suspect his neighbors might be murderers. An unbearably tense psychological horror masterpiece.",
    isNew:false, isTrending:false,
  },

  // ──── ACTION ───────────────────────────────────────────────────
  {
    id:20,
    title:"Vincenzo",
    krTitle:"빈센조",
    genre:"action",
    year:2021, episodes:20, rating:9.1,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/mVQQW5EblWL43UrxijFuDhp5BFy.jpg",
    fallback:"🇮🇹",
    cast:["Song Joong-ki","Jeon Yeo-been"],
    tags:["Mafia","Dark comedy","Villain lead","Iconic"],
    synopsis:"An Italian-Korean mafia lawyer returns to Korea and takes on a corrupt conglomerate using his own criminal methods. Slick, stylish, and outrageously entertaining.",
    isNew:false, isTrending:true,
  },
  {
    id:21,
    title:"Taxi Driver",
    krTitle:"모범택시",
    genre:"action",
    year:2021, episodes:16, rating:9.0,
    network:"SBS",
    poster:"https://image.tmdb.org/t/p/w500/4mAMBqQBxGDCMWNz7WmXXDrvsm9.jpg",
    fallback:"🚕",
    cast:["Lee Je-hoon","Esom"],
    tags:["Vigilante","Revenge","Cathartic","Justice"],
    synopsis:"A secret organization uses a taxi service as cover to deliver brutal vengeance for victims of crimes that the law failed to punish. Pure, satisfying revenge fantasy.",
    isNew:false, isTrending:false,
  },
  {
    id:22,
    title:"Itaewon Class",
    krTitle:"이태원 클라쓰",
    genre:"action",
    year:2020, episodes:16, rating:8.9,
    network:"JTBC",
    poster:"https://image.tmdb.org/t/p/w500/4BvNoJAoFEDDhMzRjFQb4qAECVb.jpg",
    fallback:"🍻",
    cast:["Park Seo-joon","Kim Da-mi"],
    tags:["Revenge","Restaurant","Underdog","Inspiring"],
    synopsis:"A passionate young man vows to destroy the food empire that ruined his family by starting from a tiny bar in Itaewon. An electric underdog story driven by pure will.",
    isNew:false, isTrending:false,
  },

  // ──── MELODRAMA ────────────────────────────────────────────────
  {
    id:23,
    title:"My Mister",
    krTitle:"나의 아저씨",
    genre:"melodrama",
    year:2018, episodes:16, rating:9.8,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/vR7hwaGDCyN7a3MoAQp9mYRkBwi.jpg",
    fallback:"🌧️",
    cast:["Lee Sun-kyun","IU"],
    tags:["Life drama","Healing","Profound","Must-watch"],
    synopsis:"A middle-aged man quietly weathering despair and a young woman hardened by hardship form an unlikely, life-changing bond. Considered by many the greatest Korean drama ever made.",
    isNew:false, isTrending:true,
  },
  {
    id:24,
    title:"It's Okay to Not Be Okay",
    krTitle:"사이코지만 괜찮아",
    genre:"melodrama",
    year:2020, episodes:16, rating:9.3,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/fRpzU3aUEhD5QHSVS5oBoQZvGtb.jpg",
    fallback:"🦋",
    cast:["Kim Soo-hyun","Seo Ye-ji"],
    tags:["Mental health","Fairy tale","Art direction","Healing"],
    synopsis:"A psychiatric ward worker meets an anti-social children's book author with a dark past. Visually gorgeous and emotionally cathartic — a journey through trauma toward healing.",
    isNew:false, isTrending:false,
  },

  // ──── HISTORICAL ───────────────────────────────────────────────
  {
    id:25,
    title:"Mr. Sunshine",
    krTitle:"미스터 션샤인",
    genre:"historical",
    year:2018, episodes:24, rating:9.5,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/6mFkhAO6bFSRJJbCrjzp6bBvWqH.jpg",
    fallback:"🌅",
    cast:["Lee Byung-hun","Kim Tae-ri"],
    tags:["Period drama","Anti-Japanese","Epic romance","Cinematic"],
    synopsis:"A boy born into Joseon slavery returns as a US military officer and falls for a noblewoman fighting against Japanese colonization. Breathtaking, heartbreaking, and epic in every sense.",
    isNew:false, isTrending:false,
  },
  {
    id:26,
    title:"Under the Queen's Umbrella",
    krTitle:"왕후의 우산 아래",
    genre:"historical",
    year:2022, episodes:16, rating:9.1,
    network:"tvN",
    poster:"https://image.tmdb.org/t/p/w500/jIlJcZQOxAa8SBBpTe2zGPD7Ade.jpg",
    fallback:"☂️",
    cast:["Kim Hye-soo","Choi Won-young"],
    tags:["Queen","Palace politics","Strong female lead","Gripping"],
    synopsis:"A queen fights to protect her sons and survive the ruthless politics of the Joseon royal court. Powerful, witty, and utterly gripping palace drama at its finest.",
    isNew:false, isTrending:false,
  },
];
